
name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, macos-11.0]
        xcode: ['12.3', '12.4', '12.5']
        build_type: ['debug', 'release']
        exclude:
          - os: macos-10.15
            xcode: '12.5'
    runs-on: ${{ matrix.os }}
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Bundle install
        run: |
          bundle install
      - name: Fastlane build
        run: |
          bundle exec fastlane build_${{ matrix.build_type }}
